### ISSUE TITLE
Test using Shapeit4 with --use-PS option

### ISSUE THREAD

**Issue by rlorigro** [broadinstitute/lrma-aou1-panel-creation#14]
As @hangsuUNC identified, Shapeit4 has an option to respect phase blocks, we should see if it helps with incompatible haplotype generation

**Comment by rlorigro** [comment]
Very curious about the results from this. Does `--use-PS` affect the incompatible alleles?

**Comment by samuelklee** [comment]
See the comments in the PR, it appears to have a positive effect. Although it might be nice to see this vary as a function of the argument and perhaps also over a larger region.
