### ISSUE TITLE
PhysicalAndStatisticalPhasing.ConvertLowerCase crashes on latest hapestry + small var output

### ISSUE THREAD

**Issue by rlorigro** [broadinstitute/lrma-aou1-panel-creation#53]
`convert_lower_case.py` appears to be expecting an INFO field that is not guranteed to be present for all vars

```
  File "/cromwell_root/truvari_intrasample/convert_lower_case.py", line 35, in convert
    if sv_type == "UNK" or sv_type == "CNV":
       ^^^^^^^
UnboundLocalError: cannot access local variable 'sv_type' where it is not associated with a value
2024/10/04 16:10:56 Starting delocalization.
```

**Comment by rlorigro** [comment]
One of the failed inputs if helpful:

gs://fc-c6ae4a57-f44e-4d6c-befd-c48a2abcecc7/submissions/5cdb0873-241e-4e50-9dcb-9d2843042f42/PhasedPanelEvaluation/31d29963-e33b-4b7e-895d-037e0f37fc8d/call-PhysicalAndStatisticalPhasing/PhysicalAndStatisticalPhasing/9fbb7f6d-c335-4ae2-b7f5-8d3c7b0b7431/call-SplitVcfbySampleSV/shard-0/HG002.subset.g.vcf.gz

**Comment by hangsuUNC** [comment]
Done!

**Comment by rlorigro** [comment]
thanks! looks like its working :+1:
